"""create llm_mapping table

Revision ID: 8fc4e72f6e5a
Revises: 0295b84f9ca6
Create Date: 2026-02-27 11:00:35.734377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8fc4e72f6e5a'
down_revision: Union[str, Sequence[str], None] = '0295b84f9ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loaners',
    sa.Column('loaner_id', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('mobile_no', sa.String(length=20), nullable=True),
    sa.Column('loaner_adhar', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_land', sa.String(length=50), nullable=True),
    sa.Column('descrition', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('loaner_id')
    )
    op.drop_table('llm_mapping')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_mapping',
    sa.Column('loaner_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fullname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mobile_no', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('loaner_adhar', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_land', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('descrition', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('loaner_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('loaners')
    # ### end Alembic commands ###
